client_config_backend: settings
client_config:
    client_id: 26724933340-esfmgosl4e0mg68k47gr2tr6q6dag0pt.apps.googleusercontent.com
    client_secret: ykhzU1zwmPfg8fAeups6inaM: True
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
    - https://www.googleapis.com/auth/drive.file